version: "3.8"
services:
  nginx_service:
    image: nginx:1.19.1-alpine
    container_name: async_task_hub_nginx
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    ports:
      - "8082:9090"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/ssl:/etc/nginx/ssl:ro
      - ./data/log/nginx:/var/log/nginx:rw
    environment:
      TZ: Asia/Shanghai
    networks:
      - default

  app_service:
    build: .
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 3s
      resources:
        limits:
          memory: 1024M
    expose:
      - "9090"
    volumes:
      - ./data/log:/app/data/log/:rw
      - ./data/uploads:/app/data/uploads/:rw
    environment:
      - TZ=Asia/Shanghai
      - APP_ENV=${APP_ENV}
      - APP_URL=${APP_URL}
      - APP_LOG_MODE=${APP_LOG_MODE}
      - APP_LOG_FILENAME=${APP_LOG_FILENAME}
      - DATABASE_DRIVER=${DATABASE_DRIVER}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_CHARSET=${DATABASE_CHARSET}
      - DATABASE_MAX_IDLE_CONNS=${DATABASE_MAX_IDLE_CONNS}
      - DATABASE_MAX_OPEN_CONNS=${DATABASE_MAX_OPEN_CONNS}
      - DATABASE_LOG_MODE=${DATABASE_LOG_MODE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    networks:
      - default

networks:
  default:
