version: "3.8"
services:
  tkerland_nginx_service:
    image: nginx:1.19.1-alpine
    container_name: tkerland_nginx
    ports:
      - "8082:8080"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/ssl:/etc/nginx/ssl:ro
      - ./data/log/nginx:/var/log/nginx:rw
    environment:
      TZ: Asia/Shanghai
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    depends_on:
      - tkerland_app_service

  tkerland_app_service:
    build: .
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 3s
      resources:
        limits:
          memory: 1024M
    expose:
      - "9090"
    volumes:
      - ./data/log:/app/data/log/:rw
      - ./data/uploads:/app/data/uploads/:rw
    environment:
      - TZ=Asia/Shanghai
      - APP_ENV=${APP_ENV}
      - APP_URL=${APP_URL}
      - APP_LOG_MODE=${APP_LOG_MODE}
      - APP_LOG_FILENAME=${APP_LOG_FILENAME}
      - DATABASE_DRIVER=${DATABASE_DRIVER}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_CHARSET=${DATABASE_CHARSET}
      - DATABASE_MAX_IDLE_CONNS=${DATABASE_MAX_IDLE_CONNS}
      - DATABASE_MAX_OPEN_CONNS=${DATABASE_MAX_OPEN_CONNS}
      - DATABASE_LOG_MODE=${DATABASE_LOG_MODE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    networks:
      - default
    depends_on:
      - tkerland_mysql_service
      - tkerland_redis_service

  tkerland_mysql_service:
    image: mysql:8.0.13
    container_name: tkerland_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./services/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql:/var/lib/mysql/:rw
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

  tkerland_redis_service:
    image: redis:5.0.3-alpine
    container_name: tkerland_redis
    ports:
      - "6379:6379"
    volumes:
      - ./services/redis/redis.conf:/etc/redis.conf:ro
      - ./data/redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: Asia/Shanghai
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

networks:
  default:
