version: "3.8"
services:
  async_task_hub_nginx:
    image: nginx:1.19.1-alpine
    container_name: async_task_hub_nginx
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
    ports:
      - "8083:9090"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/log:/var/log/nginx:rw
    environment:
      TZ: Asia/Shanghai
    networks:
      - default

  async_task_hub_app:
    build: .
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
    expose:
      - "9090"
    volumes:
      - ./data/log:/app/data/log:rw
    environment:
      - TZ=Asia/Shanghai
      - BASE_PATH=${BASE_PATH}
      - APP_ENV=${APP_ENV}
      - APP_LOG_MODE=${APP_LOG_MODE}
      - APP_LOG_FILENAME=${APP_LOG_FILENAME}
      - DATABASE_DRIVER=${DATABASE_DRIVER}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_CHARSET=${DATABASE_CHARSET}
      - DATABASE_MAX_IDLE_CONNS=${DATABASE_MAX_IDLE_CONNS}
      - DATABASE_MAX_OPEN_CONNS=${DATABASE_MAX_OPEN_CONNS}
      - DATABASE_LOG_MODE=${DATABASE_LOG_MODE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PREFIX=${REDIS_PREFIX}
    networks:
      - default

networks:
  default:
